---
# SPDX-License-Identifier: CC0-1.0
# vi: ts=2 sw=2 et:

name: Lint Code Base
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
        with:
          # We need a full repo clone to get a correct list of changed files
          fetch-depth: 0
        # FIXME: super-linter doesn't recognize perl/python scripts without
        #        an extension; let's workaround it by creating a dummy symlink
        #        directory with necessary extensions until it's resolved.
        #        The `find` below just checks if all symlinks in the dummy
        #        directory are valid.
      - name: Check test-related symlinks
        run: find .github/super-linter-links/ -type l -exec ls -L {} +
      - name: Lint Code Base
        uses: github/super-linter/slim@latest
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MULTI_STATUS: true
          # FIXME: until the above FIXME is resolved, we need to always check
          #        the whole codebase, otherwise only changed files would be
          #        considered, which would ignore the symlinked files. Since
          #        we have only couple of files to check, it's not an issue
          #        (yet).
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_PERL: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_PYLINT: true
